### ISSUE TITLE
No package example_robot_data

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#1]
I've installed crocoddyl from the robotpkg binaries and it is correctly sourced. The package `robotpkg-example-robot-data` is installed. However, I get:

```
Traceback (most recent call last):
  File "bipedal_walking_from_foot_traj.py", line 6, in <module>
    import example_robot_data
ImportError: No module named example_robot_data
```

**Comment by cmastalli** [comment]
I think you should upgrade robot-example-data. Did you do it?

**Comment by wxmerkt** [comment]
Yes... I just installed and it's the latest version on the binaries (2.0.0).

Also, the croccodyl version doesn't import any of the action models:

```
Traceback (most recent call last):
  File "jump.py", line 21, in <module>
    from crocoddyl import (ActionModelImpact, ActivationModelInequality, ActivationModelWeightedQuad,
ImportError: cannot import name ActionModelImpact
```

Is it possible that the build server hasn't released the new binaries yet?

**Comment by cmastalli** [comment]
@nim65s can tell you more about the binary release. I didn't try it myself yet.

There are few classes that haven't been release yet, e.g.:
 - ActionModelImpact,  ImpactModel3D, ImpactModel6D
 - ActivationModelInequality,
 - SolverFDDP, among others.

We tagged this version 0.9.0 because there is not yet everything there.

**Comment by cmastalli** [comment]
Regarding the examples and notebooks, it almost everything working with the exception of:
 - jump.py
 - walk.py
 - salto.py

The problem with these examples is we need to release some of the classes that I mentioned above.

**Comment by wxmerkt** [comment]
Similarly @nim65s, the 2.0.0 tag on `example-robot-data` in the binaries does not contain the Python loader either.

**Comment by wxmerkt** [comment]
@cmastalli thank you for the update! Looking forward to Guilhem's response and will re-try then.

**Comment by nim65s** [comment]
@wxmerkt Python loaders are available in `robotpkg-pyXY-example-robot-data`, depending of your major / minor version of python.

I am fixing the dependency from `robotpkg-pyXY-crocoddyl` to `robotpkg-pyXY-example-robot-data` right now.

**Comment by cmastalli** [comment]
I added in the README file instruction of how to install the Python loaders in example-robot-data. This information also appears in the README file of Crocoddyl.

**Comment by cmastalli** [comment]
I believe this issue has been solved. If not, feel free to reopen it
