### ISSUE TITLE
Proper way to use State limits (joint position/velocity)

### ISSUE THREAD

**Issue by egordv** [loco-3d/crocoddyl#1012]
Hello and thank you once again for a great framework!

I'm doing my best to master it, but I'm stuck in implementing state-space joint limits (joint position and velocity) for biped platform.

The cost model which looks suitable for this ("CostModelSoftStateLimits") was removed by [this commit](https://github.com/loco-3d/crocoddyl/commit/2ced5194b4d47b04390c17c3ded008daee9c61a2) alongside with refactoring of cost model paradigm.

What should I use instead of missing "CostModelSoftStateLimits" to properly implement the position/velocity joint limits in recent version of crocoddyl? Should I take a bare "CostModelState" and re-implement abandoned "CostModelSoftStateLimits" in my code?

**Comment by cmastalli** [comment]
You're looking into a beta version of Crocoddyl, which we haven't release to the public.
This version was purely implemented in Python, and we did our first public release with a c++ implementation library.

Furthermore, you shouldn't neither re-implement this function as
 1. We have a current solution
 2. This kind of information is encoded in a residual vector.

Please get inspiration from this code: https://github.com/loco-3d/crocoddyl/blob/devel/bindings/python/crocoddyl/utils/quadruped.py#L476-L480

I'll close this issue as I have provided an explanation.
If there are still doubts, then feel free to ask them here.
