### ISSUE TITLE
Error generation when built from source files (needed for compilation on Windows)

### ISSUE THREAD

**Issue by xeonz1** [loco-3d/crocoddyl#1014]
CMake Error: INSTALL(EXPORT) given unknown export "crocoddylTargets"

The crocoddyTargets.cmake file thus is not generated

**Comment by cmastalli** [comment]
@nim65s  -- could you develop the needed bits to make Crocoddyl compatible with Windows?

**Comment by cmastalli** [comment]
What is the status of this issue?
