### ISSUE TITLE
ActionModelNumDiff does not use the control bounds defined in model

### ISSUE THREAD

**Issue by quimortiz** [loco-3d/crocoddyl#1052]
Minor: it seems that ActionModelNumDiff does not use the control bounds defined in the model that you pass in the constructor (member variable model_ in c++ code). Is that intended? Thanks for the library!

**Comment by cmastalli** [comment]
Hi @quimortiz!

We use the action numdiff for unittesting only. That's the reason why we haven't added this support.

But I see the benefit for users to add such kind of feature. I will include it asap.

Is this fine for you?

**Comment by quimortiz** [comment]
Thanks! Yes sure, it is not urgent. For now, I am defining the bounds on the ActionModelNumDiff object.

**Comment by wxmerkt** [comment]
Isn't this fixed in `devel` by https://github.com/loco-3d/crocoddyl/pull/1048?

**Comment by cmastalli** [comment]
You're right @wxmerkt!

@quimortiz -- we haven't released this code, but you could get it if you compile the devel branch.

I will close this issue!
