### ISSUE TITLE
MPC example 

### ISSUE THREAD

**Issue by hclin77923** [loco-3d/crocoddyl#1071]
Hello, 

Thank you for providing such a good optimal control library for manipulation and locomotion. 

I notice from the discussion in Issues #674 #772 #782 and some literature (https://hal.archives-ouvertes.fr/hal-02993058v2/document) that using Crocoddyl to implement an MPC controller. I wonder whether you can provide an example such as arm manipulation or legged robot locomotion to perform MPC with Crocoddyl. Thanks in advanced for your answer.

**Comment by cmastalli** [comment]
Thank you for being interested in our project.

We have developed at least 4 MPC libraries based on Crocoddyl in different teams. I particularly developed this one: https://arxiv.org/abs/2203.07554#:~:text=Achieving%20agile%20maneuvers%20through%20multiple,nonholonomy%20of%20the%20kinetic%20momenta.

However, we are not planning to open source them for now.
