### ISSUE TITLE
 include Ipopt in gitlab-ci

### ISSUE THREAD

**Issue by nim65s** [loco-3d/crocoddyl#1076]
@nim65s -- can you help me to include Ipopt in gitlab-ci?

**Comment by cmastalli** [comment]
Hi @nim65s -- do you have any update regarding this topic?

**Comment by cmastalli** [comment]
Recently, I have included a CONDA job that tests Ipopt. However, it would be still nice to have it in gitlab-ci. @nim65s -- is this possible in the short term? Thanks

**Comment by nim65s** [comment]
Yes, this should be done next week or the one following

**Comment by cmastalli** [comment]
> Yes, this should be done next week or the one following

Fantastic! Merci beaucoup :)
