### ISSUE TITLE
Geometric model error

### ISSUE THREAD

**Issue by prakrutk** [loco-3d/crocoddyl#1077]
ValueError: Argument geometry_model should be a GeometryModel 

When I am trying to import a custom model in crocoddyl using:
model_name = example_robot_data.load('model')
robot_model = model_name.model

I have also added the robot loader class for this model and all the model files in the example data folder. And this file I am able to import in other simulatiors. So I guess the mesh files are correct. Is there anything else I need to change to import a custom model. Or is there any other way? 

Thanks

**Comment by cmastalli** [comment]
Hi @prakrutk 

I appreciate your interests in our library. However, this is an issue with your custom model (we don't maintain it) implemented in another package. You can still ask questions that helps you to deal with your code, but this should be done in the example-robot-data or Pinocchio repositories.

Thank you so much for understanding. (I need to close this issue)
