### ISSUE TITLE
ModuleNotFoundError: No module named 'crocoddyl.libcrocoddyl_pywrap'

### ISSUE THREAD

**Issue by huihuishen** [loco-3d/crocoddyl#1078]
try to run bipedal_walk.py using the source code file, i got the wrong error. Can somebody help? Thanks!

**Comment by cmastalli** [comment]
Hi @huihuishen 

Thank you so much for your interests in our project.
However, there is no still enough information about your issue.

Please check that you have defined the Python path where you decided to install Crocoddyl.

Be also aware that you can install Crocoddyl using pip, conda, and robotpkg.
You can find instructions of how to do it in the Readme file.
