### ISSUE TITLE
Access to the solution of each iteration

### ISSUE THREAD

**Issue by Schortenger** [loco-3d/crocoddyl#1086]
Hi, I want to get the results (x and u) of each iteration. 
But I cannot find how to achieve this in the tutorials. Is there anyone who knows how to make it?

**Comment by Schortenger** [comment]
Oh sorry, I think I know it. I will close this issue.

**Comment by cmastalli** [comment]
Just to clarify anyone regarding this aspect. You can write a Callback function to store any solver data.
