### ISSUE TITLE
Cost increases when using 'crocoddyl.SolverFDDP'

### ISSUE THREAD

**Issue by Schortenger** [loco-3d/crocoddyl#1087]
Hi,
I'm using `crocoddyl.SolverFDDP(problem)` to solve an OCP, but the cost increases at some iterations. Is this solver using line search? If so, how can the cost go increasing? 
Looking forward to the reply. Thanks~

**Comment by cmastalli** [comment]
The solver handles dynamic feasibility as well. This is in contrast to the classical DDP algorithm. It means that it could increase a little the cost as a trade-off to decrease the infeasibility.

This behaviours can appears in line search procedure, so this is orthogonal. However, answering your question, FDDP performs a rollout of the dynamics, which can be interpreted as nonlinear search.

For more details see: https://arxiv.org/pdf/1909.04947.pdf.

I will close this issue, but do not hesitate to ask further questions if it is needed.
