### ISSUE TITLE
I want a C++ example 

### ISSUE THREAD

**Issue by MuziYT** [loco-3d/crocoddyl#1092]
I haven't found an example based on C++. Can someone give me one?Thank you.

**Comment by cmastalli** [comment]
Unfortunately, we do not have c++ examples as they are not an easy way to learn. However, it should be fairly simple to rewrite our examples in Python to c++ code. The API is the same.

Furthermore, we do not have the resources to implement such examples as we are focusing our limited resources on extending the capabilities of Crocoddy.

But this should not block you as you could also learn how to write c++ code by reading the unit-tests code.
