### ISSUE TITLE
Crocoddyl/unicycle.py - where is it located?

### ISSUE THREAD

**Issue by ThorbenPultke** [loco-3d/crocoddyl#1094]
Hey!

Thank you so much for your great framework. I'm just getting started with it and currently trying to implement the unicycle-model to compare it against acados for my thesis. I somehow cannot get it working - it just won't optimize (stays at 0 all the time) the second control action (omega). Since you provided an example with exactly the same problem, I wanted to take a look at your implementation of the unicycle-model, but cannot locate the file (unicycle.py) which the corresponding jupyter notebook refers to. A short google search led me to this, i assume, highly outdated implementation: [https://gitlab.iri.upc.edu/jmarti/crocoddyl/-/blob/master/crocoddyl/unicycle.py](url).

could you point me towards the right file, so I can proceed my research?

Best regards!

**Comment by cmastalli** [comment]
Hi @ThorbenPultke,

I assumed you tried to implement the unicycle from your side, but it doesn't converge, right?

The unicycle model used in our notebook (e.g., https://github.com/loco-3d/crocoddyl/blob/master/examples/notebooks/unicycle_towards_origin.py) is implemented in c++. However, we have a Python version for the sake of testing here: https://github.com/loco-3d/crocoddyl/blob/master/bindings/python/crocoddyl/utils/__init__.py#L179-L219

I hope this help you. I believe this issues can be closed.
