### ISSUE TITLE
Python: ShootingProblemTpl -> no set_x0() function

### ISSUE THREAD

**Issue by ThorbenPultke** [loco-3d/crocoddyl#1095]
Hi there! I really hope that I don't open an issue that has already been adressed.

As I am proceeding with getting to know crocoddyl for my MPC project, I tried to implement a rudimentary MPC for a manipulator. I checked the docs for the ShootingProblemTpl class template reference and found the built-in function .set_x0(), but it seems like it is not implemented in the python bindings? Since python is what i am currently prototyping with, is there something I am missing? If so, could you point me in the right direction?

Thank you in advance!

**Comment by cmastalli** [comment]
Hi @ThorbenPultke!

You can also get or set the value of 'x0' in Python. This is how you do:
```python
problem.x0 = #numpy array
```

I will close the issue as this answer your question.

I hope you find our software useful and helps to improve it.
