### ISSUE TITLE
Crocoddyl does not work with numpy anymore (np.__version__ >= 2.23)

### ISSUE THREAD

**Issue by ymontmarin** [loco-3d/crocoddyl#1105]
Hello,

Just to let you know that numpy has decide to remove the method `np.asscalar` that was deprecated since 1.16 and is removed from 2.23. The method in 7 files in crocoddyle. In current versioning on conda for pinocchio, it prevents using python 3.11.

I patched the conda recipe https://github.com/conda-forge/crocoddyl-feedstock/pull/24 waiting for upstream fix.

Best,
Yann

**Comment by cmastalli** [comment]
Hi @ymontmarin

I am not familiar with the development in conda. But you might be aware that we have already sorted out this issue (which includes other modifications in these files) in an ongoing branch to be merged.

I hope your patch doesn't create future conflicts with what will merge later.

**Comment by nim65s** [comment]
Hi @ymontmarin,

Instead of pinning numpy to old versions, could you apply #1106 as patch on conda ?
NB: github allows to directly get a patch from a PR by adding `.patch` at the end of the url: `https://github.com/loco-3d/crocoddyl/pull/1106.patch`

**Comment by ymontmarin** [comment]
@nim65s @cmastalli thank you ! I pinned the version because asscalar was maybe not the only compatibility issue. But as you  confirm, I used a patch instead: https://github.com/conda-forge/crocoddyl-feedstock/pull/25

Thank you !
