### ISSUE TITLE
Time optimal trajectories

### ISSUE THREAD

**Issue by diarodriguezva** [loco-3d/crocoddyl#1147]
Hi,
Thank you for sharing this library. It helps a lot the community. 

I want to implement time optimal trajectories by adding `dt` into the control variables and by adding a corresponding cost function. I am considering creating a new `ActuationModel` that incorporates time such that I can use it in the cost function. I assume I would also need to implement a class for the `IntegratedActionModel` in order to consume the optimized time for the integration. Is this a good way to tackle this problem, or is there any other simpler way ?

**Comment by cmastalli** [comment]
Hi @diarodriguezva! I think so.
