### ISSUE TITLE
Wrong dimension for ResidualModelState.set_reference()

### ISSUE THREAD

**Issue by ComePerrot** [loco-3d/crocoddyl#1157]
Hello,

I'm running into a bug when using the _set_reference_ method of _ResidualModelState_ on version 2.0.1:
```
void crocoddyl::ResidualModelStateTpl<Scalar>::set_reference(const VectorXs&) [with _Scalar = double; crocoddyl::ResidualModelStateTpl<Scalar>::VectorXs = Eigen::Matrix<double, -1, 1>] 151
Invalid argument: the state reference has wrong dimension (63 provided - it should be 62)
```

The same code was previously running without problems on release 1.9.0.

The dimension of the reference I'm providing doesn't match the one expected by Crocoddyl.
I believe there is an error in the check carried out in file [state.hxx](https://github.com/loco-3d/crocoddyl/blob/master/include/crocoddyl/multibody/residuals/state.hxx#L150).
It should be:
`static_cast<std::size_t>(reference.size()) != state_->get_nx()`
instead of
`static_cast<std::size_t>(reference.size()) != nr_`

It fixes the issue in my case, where `state_->get_nx() = nr_+1`.

I haven't checked the other residuals, but I think this is the only one where this kind of problem would arise.

### System

- OS: Ubuntu 20.04
- Crocoddyl version: 2.0.1

**Comment by cmastalli** [comment]
Thanks for reporting this bug, @ComePerrot !

Above you can see the PR that solves it.
Need to create some unit test for this.
