### ISSUE TITLE
Actual Cost Values Inside CostModelSum

### ISSUE THREAD

**Issue by Cfather** [loco-3d/crocoddyl#1209]
Hi, 

I was running a bunch of examples in humanoids. I noticed that you used `CostModelSum` to describe the walking problem (defined in biped.py) and add different costs, such as a contact model to maintain contacts and swing foot or com tracking to achieve some tasks. I ran the code and the total cost decreased a lot. I have got two specific questions:
1. I wonder if I can extract the values of these different cost models in the solution so that I can understand which one is optimized well and which one is not.
2. How should I choose the weights of different cost models in principle? These weights seem to change the quality of the solution and the solve time dramatically.

Thanks!

**Comment by cmastalli** [comment]
Hi @Cfather,

1. It is possible to extract cost values and derivatives for individual cost functions.
2. Tuning the weights requires experience. One suggestion is tuning one weight at a time.

Regards,
Carlos
