### ISSUE TITLE
Understanding the Outputs of crocoddyl

### ISSUE THREAD

**Issue by Cfather** [loco-3d/crocoddyl#1210]
Hi, 

I ran some examples of crocoddyl. I noticed that the outputs listed the evolvement of the following variables with respect to the iterations:
1. cost       
2. merit      
3. stop       
4. grad       
5. preg       
6. dreg      
7. step   
8. ||ffeas||  
9. ||gfeas||  
10. ||hfeas||   
11. dV-exp       
12. dV      
13. dPhi-exp     
14. dPhi
Could I get a brief explanation of what these variables mean? I appreciate it very much!

**Comment by cmastalli** [comment]
Hi @Cfather!

We have documented these variables in both Python and C++ interfaces. Please take a look yourself, for instance, at https://github.com/loco-3d/crocoddyl/blob/master/bindings/python/crocoddyl/core/solver-base.cpp#L177-L220.

We have limited resources and are focusing on exciting new features in Crocoddyl. We are aware that it is needed to develop a website providing more detailed documentation. We welcome anyone who wants to help us with this task.
