### ISSUE TITLE
Modeling Hand-Object Contacts

### ISSUE THREAD

**Issue by fukangl** [loco-3d/crocoddyl#1218]
I am currently working on whole body manipulation in contact-rich scenarios in Crocoddyl. I have noticed that in all examples, there is just one robot in the environment, and the contacts are between the feet of the robot and the ground. I am curious about Crocoddyl's capability to model contacts between the robot and objects. For example, there is a table on the environment, and some objects are placed on the table. If the task involves the robot grasping an object from the table, I can load the URDF files for both the table and the objects.  My question is, how do I model the contacts between the robot's hands and the object? This includes defining the state, actuation, and contacts, etc. Any guidance would be helpful. I really appreciate that.

**Comment by cmastalli** [comment]
Let's keep this conversation private.
