### ISSUE TITLE
Some confusion about cost

### ISSUE THREAD

**Issue by lrchit** [loco-3d/crocoddyl#1236]
Hi,
I'm trying to use FDDP on quadrupedal robot, but I have some confusion about cost. 
1. I wonder what reference should be set to state residual model. I firstly guess this should be the desired full configuration of the robot, which should be gained through inverse kinematics, but I found it very inefficient to do inverse kinematics things for every shooting node. So may it be the default state when the robot is standing? If so, doesn't this potentially conflict with the foot tracking task? 
2. I'm also confused that if the tasks (com task and foot tracking task) is weighted or hierarchical. Or are low-level tasks projected onto the null space of high-level tasks so the order in which tasks are defined would make a difference? I meet some difficulties with adjusting parameters so I really want to know what's the relationship between state regularization and tasks. Also, how does crocoddyl deal with inequality constraints? My initial understanding is that they're handled by some penalty function (as well as augmented Lagrangian or interior point method), so the weight of constraints cost matters a lot.

Thanks a lot for your attention!

**Comment by cmastalli** [comment]
Hi @lrchit,

1. I suggest reading our MPC papers: (1) https://arxiv.org/pdf/2203.07554.pdf?trk=public_post_comment-text, (2) https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=10101674, (3) https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=10160333, and (4) https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=10366250 to educate yourself on MPC formulations. As a general comment, cost could serve for tracking or regularizing tasks.
2. As you can see in our papers, including Crocoddyl one in https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9196673, the cost is "weighted" and not "hierarchical". In the future, we'll release an advanced solver for handling inequality constraints. Currently, Crocoddyl handles control limits only as hard constraints. Other inequality constraints can be formulated through quadratic penalties.

I hope Crocoddyl helps you in your research. For now, you need to be patient as we'll release our current research works later.

Thanks,
Carlos
