### ISSUE TITLE
Update the doxygen for the new version

### ISSUE THREAD

**Issue by mingu6** [loco-3d/crocoddyl#1246]
Hi,

Awesome library, great work! 

Would it be possible to update the hosted doxygen documentation to the latest version? I would like to see the updates to the interface for constraints. Any assistance would be appreciated.

Thanks!

**Comment by nim65s** [comment]
Hi @mingu6,

I thought this was already fixed, thanks for the heads-up !

**Comment by nim65s** [comment]
Ok I guess this doesn't help:
https://github.com/loco-3d/crocoddyl/blob/5b415a16138d01cf43118b38f64dbb6ad535b61b/CMakeLists.txt#L11

**Comment by nim65s** [comment]
done :)

**Comment by mingu6** [comment]
Confirmed, thanks a lot! :)
