### ISSUE TITLE
Questions about ConstraintModel class

### ISSUE THREAD

**Issue by jia-xinyu** [loco-3d/crocoddyl#1267]
Hi,

Thanks for developing such a great OP solver. I am writing a constrainted MPC based on the Crocoddyl, and noticed that the v2 version added the `ConstraintModelResidual` class. So I wonder how the solver handles inequality constraints using this class (or its principal). Its `calc()` function seems to provide little informtion. Are the constraints formulated as _quadratic penalties_ in the cost as in the [example](https://github.com/loco-3d/crocoddyl/blob/da92f67394c07c987458a8cb24bc0e33edd64227/examples/humanoid_manipulation.py#L89C1-L89C10)? If so, how how do I adjust the weights for these penalty functions?

Thanks a lot!

**Comment by cmastalli** [comment]
Hi @jia-xinyu,

Let's take this discussion in private. Please feel free to contact me via c.mastalli@hw.ac.uk.
