### ISSUE TITLE
Translation component for foot task in jumping problem

### ISSUE THREAD

**Issue by MR-KNV** [loco-3d/crocoddyl#1287]
Hello,
Thanks for such great library!
I think that I found a mistake in ```biped.py``` module.  
Now, when you create a ```pin.SE3``` instance for foot task in jumping problem, a translation component is equal ```self.lfId + f0``` for left leg (and ```self.rfId+f0``` for right one).
I think that correct form is ```lfFootPos0+f0``` for left leg (and ```rfFootPos0+f0``` for right one). 
With current description jumping problem doesn't work.

https://github.com/loco-3d/crocoddyl/blob/da92f67394c07c987458a8cb24bc0e33edd64227/bindings/python/crocoddyl/utils/biped.py#L173-L176

**Comment by cmastalli** [comment]
Thanks for reporting, @MR-KNV! This has been fixed in https://github.com/loco-3d/crocoddyl/pull/1288.
