### ISSUE TITLE
Using a custom differential action model

### ISSUE THREAD

**Issue by lrchit** [loco-3d/crocoddyl#1304]
Hi,

I'm using a custom "differential action model" to try to have a better understanding about `crocoddyl`. I choose contact forces and joint torques as inputs, and calculate forward dynamics with `pinocchio` and its derivatives with `cppadcodegen`. Currently I only activate state and control residual, without any constraints and other costs and setting zero torque to the `quadruped robot` in `mujoco` to preliminarily test whether the solution is reasonable. The problem is that the solver seems to have converged after a few calls because it returns the same solution, but the value seems to make no sense. Does this mean the solver failed and there's something wrong with my implementation? It returns differently if I pull the robot up.

My another confusion is that, what frequency should mpc be set to? I use `DifferentialActionModelContactFwdDynamicsTpl` on quadruped robot with 40 nodes and iterate 4 times of `FDDP` each time. This takes 18ms on average and thus I call the sollver at 50Hz. May it be called immediately right after last call is finished? If it needs to run at a fixed frequency, how is its computational time considered? There's an inevitable delay between the solution and the real control command, right?

Looking forward to your answer and thank you in advance!

Best, 
Ruochen

**Comment by cmastalli** [comment]
Hi @lrchit,

We have limited resources constraining us to not provide feedback on someone's else code. If you want to learn how to write a differential action model, then please see this file https://github.com/loco-3d/crocoddyl/blob/master/examples/notebooks/cartpole_swing_up.py. However, I must tell you that this class will be deprecated in Crocoddyl v3.

You can see the details of our MPC setup at https://arxiv.org/pdf/2203.07554 and https://arxiv.org/pdf/2209.05375. This could help you to setup your own MPC.

Best,
Carlos
