### ISSUE TITLE
Enabling writing of internal data in Eigen object for Python bindings

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#184]
In GitLab by @cmastalli on Jun 28, 2019, 16:04

For more information about it see: https://github.com/stack-of-tasks/eigenpy/issues/65.

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Jun 28, 2019, 16:05

changed the description

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Jun 28, 2019, 16:05

@ MaximilienNaveau and @hammoudbilal feel free to tackle this issue in eigenpy, just let me know if that the case.

Otherwise I will try to solve it in my free time.

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Jun 28, 2019, 16:05

mentioned in merge request !171

**Comment by cmastalli** [comment]
Solved in #715
