### ISSUE TITLE
Remove Eigen dynamic memory allocation in Euler integrator

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#230]
In GitLab by @cmastalli on Aug 12, 2019, 23:59

null

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Nov 11, 2019, 23:02

assigned to @cmastalli

**Comment by cmastalli** [comment]
@proyan you have been working in the efficiency of the euler integrator.

Could you let me know if you check that there is no memory allocation?

**Comment by cmastalli** [comment]
This has been solved in #695
