### ISSUE TITLE
c++ implementation of frame lin-velocity + bindings

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#232]
In GitLab by @cmastalli on Aug 15, 2019, 12:28

null

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Aug 15, 2019, 12:29

assigned to @cmastalli

**Comment by wxmerkt** [comment]
In GitLab by @proyan on Sep 20, 2019, 15:51

assigned to @proyan and unassigned @cmastalli

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Oct 18, 2019, 10:17

unassigned @proyan

**Comment by cmastalli** [comment]
Duplicated in #612
