### ISSUE TITLE
arm code generation + benchmark

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#265]
In GitLab by @cmastalli on Oct 4, 2019, 18:08

null

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Oct 4, 2019, 18:08

assigned to @cmastalli

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Nov 12, 2019, 16:44

unassigned @cmastalli

**Comment by cmastalli** [comment]
@proyan could you handle this task?
I would be good to have profiles for the quadruped

**Comment by wxmerkt** [comment]
Is this complete or just closed as wontdo?

**Comment by cmastalli** [comment]
I do not see any activity, and I won't do it (overbooked).

@proyan are you planning to create some benchmarks with CppAD?

**Comment by wxmerkt** [comment]
Ok, thanks, good to have this noted done as it helps to follow along whether an issue was addressed or closed as wontdo.

**Comment by cmastalli** [comment]
I tagged with #wontfix, is this sounds good for you?

**Comment by proyan** [comment]
Yes, I'm creating a benchmark with cppAD. I'm using the arm as an example.

**Comment by proyan** [comment]
Currently there is an issue with using pinocchio with code-gen. I'll make a PR next week for that. I've been quite busy with another task, so code-gen has gone back to my to-do list.

**Comment by cmastalli** [comment]
@proyan thank for pushing this task.

Could you let me know (or pointing out) the issue of Pinocchio?

**Comment by cmastalli** [comment]
Solved by #758
