### ISSUE TITLE
Add proper virtual keyword

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#278]
In GitLab by @wxmerkt on Oct 23, 2019, 12:45

Currently, the implementations of (pure) virtual functions do not carry the `virtual` keyword. This is prone to introduce bugs and also requires copy-paste/duplication in the bindings. We should add the `virtual` (C++98) or `override/final` (C++11, once switch confirmed) keywords.

**Comment by wxmerkt** [comment]
This just came back to bite me badly with overrides in Python and C++. We should make fixing the polymorphism and cleaning up the API a priority. There's a lot of duplication that can be removed with proper inheritance.

**Comment by cmastalli** [comment]
> This just came back to bite me badly with overrides in Python and C++. We should make fixing the polymorphism and cleaning up the API a priority. There's a lot of duplication that can be removed with proper inheritance.

Could you handle this task?
Unfortunately, I don't have any bandwidth to work on it before beginning of February.

**Comment by wxmerkt** [comment]
I won't have bandwidth before March. New action + contact model takes priority for me.
