### ISSUE TITLE
Generate and install CMake config

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#279]
In GitLab by @wxmerkt on Oct 23, 2019, 13:34

Analot to https://github.com/stack-of-tasks/eigenpy/issues/98, https://github.com/stack-of-tasks/pinocchio/issues/914

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Nov 1, 2019, 10:40

@wxmerkt are you handling this issue?

**Comment by wxmerkt** [comment]
In GitLab by @wxmerkt on Nov 1, 2019, 12:59

No, this requires updates and support from jrl/cmake-modules first. I would put this after ~SAB or happy for someone else to add it.

**Comment by cmastalli** [comment]
@wxmerkt is there any update regarding this?

I'm not sure what if I understand the issue, could you explain me?

**Comment by wxmerkt** [comment]
It's to update the `CMakeLists` setup so that a `crocoddyl-config.cmake` is generated such that users/dependent projects can:

```cmake
find_package(crocoddyl REQUIRED)

add_executable(example example.cpp)
target_link_libraries(example crocoddyl::crocoddyl)
```

No need for PkgConfig and setting CFLAGS_OTHERS etc.

**Comment by nim65s** [comment]
Hi,

I'm already doing this on all SoT packages, loco-3d ones will follow.

**Comment by cmastalli** [comment]
@nim65s I think you integrated this thing. Can we close this issue?

**Comment by nim65s** [comment]
yep
