### ISSUE TITLE
Standardize cost references

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#283]
In GitLab by @proyan on Nov 6, 2019, 15:04

Standardize the naming and type for cost.ref elements to: ref, Eigen::Vector.
Currently, the names and types are different based on different classes.

**Comment by wxmerkt** [comment]
In GitLab by @proyan on Nov 6, 2019, 15:24

This issue follows https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/256#note_7650

**Comment by cmastalli** [comment]
I will close this issue since it's an esthetic suggestion. After thinking about it, I decided to use specific names of each reference object.
