### ISSUE TITLE
How to install crocoddyl on Mac

### ISSUE THREAD

**Issue by ddliu365** [loco-3d/crocoddyl#3]
I followed the procedure of instructions in GitHub, but it doesn't work on Mac

**Comment by cmastalli** [comment]
Thanks for showing interest in Crocoddyl.

Unfortunately we don't Mac support yet. Nonetheless, it's in our list of priorities.

At the moment, we have very low bandwidth, and this support could take few weeks.

Could you help us to make this support and move things faster? I believe it shouldn't take so much time.

Yours,
Carlos

**Comment by ddliugit** [comment]
I will try to do that. Once it is done, I will let you know.

**Comment by cmastalli** [comment]
Great! Do not forget to start from the devel branch.

I invite you to read this wiki: https://gepgitlab.laas.fr/loco-3d/crocoddyl/wikis/Developer-Guide

**Comment by cmastalli** [comment]
Any updates regarding this topic?

**Comment by ddliugit** [comment]
I am working on that, but it doesn't work pretty well. This is the first time I am working on this. 
Do you have some materials or examples to recommend?
I would appreciate that!

**Comment by ddliugit** [comment]
For Mac I just want to the install procedure like so:

brew tap gepetto/homebrew-gepetto
brew install crocoddyl

**Comment by wxmerkt** [comment]
> For Mac I just want to the install procedure like pinocchio:

This is an actively developed project and providing a `brew` recipe may not be on the immediate timeline/horizon. After installing dependencies you can still run `mkdir build ; cd build; cmake .. ; make`.

**Comment by jcarpent** [comment]
I think copy/paste of pinocchio.rb file in https://github.com/Gepetto/homebrew-gepetto/tree/master/Formula and replacing pinocchio by the right names should make the job.

**Comment by cmastalli** [comment]
@ddliugit it would be great if you can provide the solution as @jcarpent advised you.

Unfortunately, I don't have bandwidth for working on it on short-term. If you manage to do it, then we'll welcome your PR

**Comment by ddliugit** [comment]
Thank you very much @jcarpent .
I will work on that. @cmastalli

**Comment by cmastalli** [comment]
Now it is possible to install Crocoddyl on Mac using conda as well.
I will close this issue.
