### ISSUE TITLE
New board on Github

### ISSUE THREAD

**Issue by cmastalli** [loco-3d/crocoddyl#625]
I have created a new board for easily organize the various developments / points: https://github.com/loco-3d/crocoddyl/projects/1

The board is currently organized as follows:
 1. **open**: any general topic, feature proposal or open question
 2. **c++ missing features**: a list of missing c++ classes.
 3. **unittest**: c++ unittest code and features missing in already developed c++ classes.
 4. **bugs**: reported bugs
 5. **on-going**: tasks that have been on-going with an assigned person

@wxmerkt You might be interested in solving the pending bugs.

@MaximilienNaveau you need to look and use the **unittest** board. It is completely for you :smiley: 

@proyan You might handle some of the issues in point 2, but only 1 per time.

@nmansard you can see the roadmap of the different missing features (point 2) and unittest code (point 3)

@nim65s @olivier-stasse @jcarpent fyi too

Please attach strictly to the activities in this board. It is important for the project that everyone interlocks with each other, and with it, I can easily master the team actions.

Reply this issue while you have read it. Later I will close it

**Comment by MaximilienNaveau** [comment]
Thanks Carlos for the organization of the tools! It is very helpful!
