### ISSUE TITLE
Document notation in each of the classes

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#626]
Members and scientific notation has not been referenced or documented. Sometimes it is quite hard to guess what variables are. We should document them in each header.

**Comment by cmastalli** [comment]
I have been including doxygen documentation of almost all the important classes. Is this what are you suggesting? If so, can we close this issue?

**Comment by wxmerkt** [comment]
Yep - the doxygen documentation is very comprehensive now and addresses this - good to close the issue
