### ISSUE TITLE
Contributing guidelines vs credits

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#631]
The `CONTRIBUTING.md` currently lists who has contributed in the past (list of contributors). However, GitHub interprets this special file as the "Contributing guidelines". So when someone opens an issue/pull request they are shown "Contributing guidelines", which aren't guidelines but a list of contributors. Is this intended?

![image](https://user-images.githubusercontent.com/1664508/69956687-8f7cff00-14f8-11ea-9b2c-baab5ea9fb02.png)

**Comment by cmastalli** [comment]
is this the same https://github.com/loco-3d/crocoddyl/wiki/Developer-Guide?

**Comment by wxmerkt** [comment]
Adding the content of the wiki link you said into CONTRIBUTING.md would likely do the trick (or no CONTRIBUTING.md at all). The point is: Having credits in CONTRIBUTING.md is confusing

**Comment by cmastalli** [comment]
> Adding the content of the wiki link you said into CONTRIBUTING.md would likely do the trick (or no CONTRIBUTING.md at all). The point is: Having credits in CONTRIBUTING.md is confusing

Roger that! I created an issue #634

**Comment by proyan** [comment]
I believe this is done. I'll close this.
