### ISSUE TITLE
Unit test pybinds-momemtum_cost failing on all configurations

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#650]

**Comment by jcarpent** [comment]
@proyan I think the test you mentioned in #648 are also refereed here.

**Comment by cmastalli** [comment]
What is this issue? This unit-test is passing, and you can checked here: https://travis-ci.org/loco-3d/crocoddyl/jobs/622599972

I will close this issue, feel free to reopen it.

**Comment by cmastalli** [comment]
This issue was solved it. I will close it
