### ISSUE TITLE
Missing Dependency: robotpkg-gepetto-viewer-corba

### ISSUE THREAD

**Issue by julesser** [loco-3d/crocoddyl#679]
Following up to #678:
`gepetto-gui` does not work since it is not available.
Might there be a missing dependency in the CMakeList.txt to automatically install this package?

**Comment by wxmerkt** [comment]
Crocoddyl works without the viewer on its own - it's more of an optional dependency so shouldn't be automatically installed.

**Comment by julesser** [comment]
Okay, thanks for clarification.
