### ISSUE TITLE
Displaying Robot Poses without Solving the OC

### ISSUE THREAD

**Issue by julesser** [loco-3d/crocoddyl#699]
Hi all,
I am wondering why robots do not seem to be displayed correctly in the gepetto viewer until the `.solve()` of the according shooting problem is called.

**Consider e.g. the bipedal_walking.ipynb**
Executing the script until `.solve()` gives: 
![BipedDisplayBeforeSolving](https://user-images.githubusercontent.com/58429634/75330211-09671f00-5881-11ea-8a53-fda09d05d1f6.png)
After calling `.solve()` the pose is shown correctly:
![BipedDisplayAfterSolving](https://user-images.githubusercontent.com/58429634/75330307-27348400-5881-11ea-9b63-7cfff7238b9e.png)

I came across this issue during the integration of a robot model and was irritated since the information about the reference pose is correctly parsed from the URDF.
The **related questions**:

1. Is there an existing workaround for just displaying a robot in an initial pose without solving the OC?
2. What happens in the `.solve()` method that actually effects the display?
    (thought so far they were decoupled)

**Comment by cmastalli** [comment]
> Is there an existing workaround for just displaying a robot in an initial pose without solving the OC?

Yes, it is possible. There are two ways:
  1. Directly interacting with gepetto-viewer, something like this:
```python
crocoddyl_display.robot.display(q0)
```
 2. Using the crocoddyl display (see https://github.com/loco-3d/crocoddyl/blob/devel/bindings/python/crocoddyl/__init__.py#L74):
```python
crocoddyl_display.display(xs=[q0])
```

---
>  What happens in the `.solve()` method that actually effects the display?
>   (thought so far they were decoupled)

Solver runs any callback function that it has been defined. When you active the display in the examples, then we include a callback function that display the robot in the GV at a defined iteration frequency. See this https://github.com/loco-3d/crocoddyl/blob/devel/examples/bipedal_walk.py#L59.

**Comment by julesser** [comment]
> crocoddyl_display.display(xs=[x0])

That was exactly what I was searching for - works very well.
Thanks for your explanation.

**Comment by cmastalli** [comment]
You're welcome :)
