### ISSUE TITLE
Gepetto display doesn't show the motion animation

### ISSUE THREAD

**Issue by gfadini** [loco-3d/crocoddyl#702]
Hello, I'm using the file ```arm_manipulation.py``` trying to show the motion of the arm manipulator,
however it seems to not be working for the ddp solver anymore
This:
```if WITHDISPLAY:
    display = crocoddyl.GepettoDisplay(talos_arm, 4, 4, cameraTF)
    display.displayFromSolver(ddp)
```
doesn't produce an animation
Moreover also with the fddp, GepettoDisplay doesn't show the overall motion at the end, just the callbacks.
I think this may be an easy bug to solve, @cmastalli how was the function conceived?

**Comment by cmastalli** [comment]
Hi @gfadini 

It works just the motion is very fast because you're asking the viewer to sample it. Do as follows:
```python
display = crocoddyl.GepettoDisplay(talos_arm)
display.displayFromSolver(ddp)
```

I will close this issue since there is no any bug.
Feel free to ask more question in this thread.

**Comment by gfadini** [comment]
Ok, got it, thanks
