### ISSUE TITLE
crocoddyl_LIBRARIES does not include crocoddyl

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#706]
```cmake
find_package(PkgConfig REQUIRED)
pkg_check_modules(crocoddyl REQUIRED crocoddyl)
```

And then outputting `${crocoddyl_LIBRARIES}` yields:

1. eigenpy
2. boost_python-py27
3. pinocchio
4. boost_filesystem
5. boost_serialization
6. boost_system
7. urdfdom_sensor
8. urdfdom_model_state
9. urdfdom_model
10. urdfdom_world
11. console_bridge

... but not `crocoddyl`.

**Comment by jcarpent** [comment]
Solved by #710.
