### ISSUE TITLE
Bipedal walking: CoM decreases with every gait phase

### ISSUE THREAD

**Issue by julesser** [loco-3d/crocoddyl#713]
Hi all, 
for the bipedal walking of talos there emerges an inperiodicity in the joint positions (knee, ankle joints) during a 6-step gait.
![TalosGait_Solution](https://user-images.githubusercontent.com/58429634/76529411-8940dc00-6472-11ea-95b0-7650d5cfee23.png)
This leads to a decresaing CoM with every gait phase. 
I've tried 

- Increasing the weight for the CoM cost item and 
- Increasing the weight of the state regression cost item

without success so far. 

1.) Any ideas on how to prevent the CoM decreasing?
2.) Is there a cost function to penalize differences between initial and terminal pose of the robot?

**Comment by cmastalli** [comment]
The optimal control (OC) formulation needs to be improved, and I am working on it.

With the current formulation, we build a CoM reference (for cost tracking) that starts in the initial position on the robot. However, the relative CoM positions w.r.t the foot placements varies from each OC problem. It leads with different OC problems and solutions

As mentioned in another thread, the current OC formulation is fairly simple and not done for robot deployment (only for examples). I will push a need formulation asap (it will take few weeks, unfortunatly).

**Comment by julesser** [comment]
Thanks for your quick answer. We are looking forward to progress in this direction :-)

**Comment by cmastalli** [comment]
Feel free to ask any further question if it is needed.

I will close this issue.
