### ISSUE TITLE
Cannot import name 'ActionModelImpact'

### ISSUE THREAD

**Issue by julesser** [loco-3d/crocoddyl#742]
Hi all, 
It seems to me as if the examples for highly-dynamics movements (jump.py/salto.py) became out-of-date. I wanted to report that currently both files are not executable, because of (at least) the above dependency error.
Best, 
Julian

**Comment by cmastalli** [comment]
Yes, they are backup files. We'll soon removed them!

These examples use an old API interface, based on pure Python code.

**Comment by julesser** [comment]
Okay, thanks for the comment. Will also a new version for these maneuvers be uploaded again, matching the new API interface?

**Comment by cmastalli** [comment]
> Okay, thanks for the comment. Will also a new version for these maneuvers be uploaded again, matching the new API interface?

At the moment, I have not the resource to do it. But I will attend to do it with a new formulation! Therefore, it won't look like those example codes.

**Comment by julesser** [comment]
Okay, thanks for the clarification.
