### ISSUE TITLE
AttributeError: 'CostModelContactFrictionCone' object has no attribute 'frame'

### ISSUE THREAD

**Issue by TaeilJin** [loco-3d/crocoddyl#753]
Hi 
Today I compiled a qudurpedal_gaits.py, and I got a error message "AttributeError: 'CostModelContactFrictionCone' object has no attribute 'frame'"

I am curious about this error message. Because it happens after updating robotpkg, and it also has a same error after I re-install the crocoddyl using robotpkg.

Is there a change on the crocoddyl library?

**Comment by cmastalli** [comment]
This issue is duplicate. See here for more details: https://github.com/loco-3d/crocoddyl/issues/752.
