### ISSUE TITLE
Computations Regarding Which CS?

### ISSUE THREAD

**Issue by julesser** [loco-3d/crocoddyl#764]
Hi all, 

Could you tell me in which frames the 
- twist of the floating base and the 
- spatial acceleration of the floating base 

are expressed in Crocoddyl? Is it the regarding body frame or in world coordinates?

Having this piece of information would be meaningful in order to validate the generated trajectories in other simulators.

**Comment by cmastalli** [comment]
The floating base velocity and acceleration is expressed in its body coordinate system (local frame).

Please let me know if this helped you

**Comment by julesser** [comment]
Thanks for the quick feedback.
