### ISSUE TITLE
C++ runs much slower compared to Python

### ISSUE THREAD

**Issue by tannerliu347** [loco-3d/crocoddyl#805]
Hi,

I was running the benchmark/quadrupdal-gaits-optctrl C++ example and it seemed to take a lot longer to compute compared to using Python binding. Is this normal? Thank you.

**Comment by cmastalli** [comment]
The performance is similar for both cases. If you compile the c++ library in Debug mode, then you will see a very slow performance when you compared with release mode Python binds.

Are you sure you're installing and comparing both using the same mode?

**Comment by tannerliu347** [comment]
Changing to release build did fix it. Thank you!
