### ISSUE TITLE
About cancel 'crocoddyl.switchToNumpyMatrix()'

### ISSUE THREAD

**Issue by ddliugit** [loco-3d/crocoddyl#819]
I need to integrate several piece of codes and is it possible to cancel the function `crocoddyl.switchToNumpyMatrix()` after declaring the `crocoddyl.switchToNumpyMatrix()` in the code first?

**Comment by cmastalli** [comment]
Hi @ddliugit,

We indeed want to deprecate each piece of code using numpy matrix. We have these dependencies in internal code: unittest and examples. I just wanted to point out that the library itself doesn't depend on it.

Saying that, which code are you referring? Are you using the devel branch?

Feel free to help us to migrate some code to numpy array.

**Comment by ddliugit** [comment]
Thanks. I am using the code `biped.py` and previously used some code with old version of pinocchio.

I figured that out and I will close it.
