### ISSUE TITLE
Add frame translation or rotation bound

### ISSUE THREAD

**Issue by ddliugit** [loco-3d/crocoddyl#827]
Is there a API to add the quadratic barrier function with a upper or lower bound to a specific frame?

Its purpose is to avoid geometry collision with ground or self -collision.

**Comment by cmastalli** [comment]
> Is there a API to add the quadratic barrier function with a upper or lower bound to a specific frame?

It is possible to add barrier to a given reference frame placement. You need to use the `CostModelFramePlacement` cost and the `ActivationModelQuadraticBarrier` activation.



> Its purpose is to avoid geometry collision with ground or self -collision.

The above solution won't avoid collision with a specific geometry. However, it is possible to do it but this is ongoing work.


Is this answer your questions?

**Comment by ddliugit** [comment]
Yes. It solved my problem well.
