### ISSUE TITLE
Default arguments for SolverAbstract::solve override initial guess provided via setCandidate, setRegInit

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#841]
This relates primarily to the following - but it might also be present in other places:

- `ddp.solve(xs, us)` sets the initial guess during the solve call
- `ddp.setCandidate(xs, us); ddp.solve()` overrides the previously set candidate with `[]`, `[]` - the default argument thus making `setCandidate` ineffective.

As thus, the overloaded arguments in `SolverAbstract::solve` can actually break arguments set in other places.

~[I found this while debugging some strange Python bindings issue where a Python-derived model does not get called (calc, calcDiff) if I use `ddp.solve(xs, us)` but does get called if I call `ddp.solve()`. I haven't figured out why that would be the case yet.]~ #842

**Comment by cmastalli** [comment]
>     * `ddp.setCandidate(xs, us); ddp.solve()` overrides the previously set candidate with `[]`, `[]` - the default argument thus making `setCandidate` ineffective.

This is the designed behavior, is there are reason why we shouldn't do it?
Let say that we don't expect the user run him(her)self this function since it is going to be call by `solve`.

**Comment by wxmerkt** [comment]
Makes sense and agree. I believe this was a red herring on the way to diagnosing #842.
