### ISSUE TITLE
FIx API change introduced from #857

### ISSUE THREAD

**Issue by proyan** [loco-3d/crocoddyl#872]
The change in the header files, introduced in #857 breaks downstream packages which were using the previous header structure.

@cmastalli could you please take care of this.
Could you please 
1) recreate the original files as empty header files.
2) include the new header files inside the original headers
3) and deprecate the original?

**Comment by cmastalli** [comment]
Hi @proyan,

Yes, it could. Do you have a deadline for that?
I hope this is not priority for you because I have many things in my TODO list.

In any case, I promise to handle it before the next release.
Let me know if this is fine for you :)

Best,
Carlos

**Comment by proyan** [comment]
There is never a deadline for a broken API. If it isn't fixed, people would be forced to update their code anyways.

**Comment by cmastalli** [comment]
> There is never a deadline for a broken API. If it isn't fixed, people would be forced to update their code anyways.

I will do my best.
Hopefully, I will provide a solution before the end of the next week :)

**Comment by jcarpent** [comment]
One other fast solution would be to revert the Merge #857 and then publish a new release.
I think it is important to not ask downstream users to have to change their code because some deprecated tags have been forgotten.

**Comment by nim65s** [comment]
I need this. I'll deal with it.

**Comment by proyan** [comment]
Fixed with 4a3c544
