### ISSUE TITLE
About whole body manipulation with cop constraint

### ISSUE THREAD

**Issue by ddliu365** [loco-3d/crocoddyl#880]
As the issue mention in #792, for the whole body manipulation example in `/crocoddyl/examples/whole_body_manipulation.ipynb`, should we add the zmp constraint while moving the manipulator with whole body motion for balancing torso?

Maybe the friction constraint is enough, but when should we consider adding the zmp constraint for torso balancing?

**Comment by cmastalli** [comment]
Yes, the friction constraint is not enough.
But the CoP is not enough neither.

What we need is the contact wrench cone.

**Comment by cmastalli** [comment]
Note that Crocoddyl can penalize the contact wrench cone.

**Comment by ddliu365** [comment]
I see, satisfying contact wrench cone is higher level of constraint to maintain the balance compared with cop.

**Comment by ddliu365** [comment]
I check the paper contact wrench cone from http://arxiv.org/abs/1501.04719.

Friction cone and zmp are parallel concepts to guarantee the stability, while contact wrench cone includes them as well as the bounds on the yaw torque.

Is this understanding correct?

Is there any issue if I add the contact wrench cone cost for the whole body manipulation? I see in the example code you just used the friction cone while julesser @julesser used both of them. I am confused the case when I should use these three different costs.

I am appreciated if you can provide some explanation.

**Comment by cmastalli** [comment]
> Is this understanding correct?

Yes, it is correct.

> Is there any issue if I add the contact wrench cone cost for the whole body manipulation? I see in the example code you just used the friction cone while julesser @julesser used both of them. I am confused the case when I should use these three different costs.

No, there is not.
Just note that you need to remove the friction cone cost (or CoP one) in this case.

We developed the contact wrench cone after this examples, this is the reason why we haven't yet integrated it.
We certainty need to improve the examples at some point.

In any case, note that at the moment the main objectives of the examples are
  1. to instruct the users how to use the Crocoddyl API,
  2. to check the numerical behaviors of our solver.

**Comment by cmastalli** [comment]
Btw, feel free to contribute to improve this example.

**Comment by ddliu365** [comment]
sure, thanks for your explanation which is very clear.

I am working on a whole body manipulation with high dynamic motion.

I will update the example once it works with cop or wrench cone.

**Comment by ddliu365** [comment]
I have a question about the wrench cone rotation matrix.

How to define this matrix if the foot is not aligned with the world frame?

https://github.com/loco-3d/crocoddyl/blob/b0eeaa5713166d7e6955454b90aedf0fc940baa1/bindings/python/crocoddyl/utils/biped.py#L251

For example, the foot placement is like the following:
![footplate](https://user-images.githubusercontent.com/38701021/98260150-f7319a80-1f50-11eb-90e1-79b590715c78.png)

**Comment by cmastalli** [comment]
The first element of wrench cone constructor defines the rotation of it.
