### ISSUE TITLE
'GepettoVisualizer' object has no attribute 'viewer'

### ISSUE THREAD

**Issue by YunxiTang** [loco-3d/crocoddyl#909]
when I run the examples in crocoddyl, this error appeared. But without viewer, it works.

**Comment by cmastalli** [comment]
Did you launch the Gepetto viewer in another terminal (with `gepetto-gui`)?

**Comment by YunxiTang** [comment]
Oops! Thanks for your help! I forgot to launch Gepetto viewer. It is working now. Thx!
