### ISSUE TITLE
Condensing contact control gravity and control gravity

### ISSUE THREAD

**Issue by cmastalli** [loco-3d/crocoddyl#916]
Now I am working on the residual functions for both terms; however, I noticed that it is possible to condense these two residuals into one.

Is there a reason to run control gravity (without fext) in a contact/impulse forward dynamics?
If the answer is no, then we should condense both residuals in order to simply our code.

@proyan and @edantec -- could you answer this question asap?

**Comment by proyan** [comment]
> Is there a reason to run control gravity (without fext) in a contact/impulse forward dynamics?

Could you clarify what you mean? I'll close this issue, and let's discuss this in chat.
