### ISSUE TITLE
CoP constraint with Z rotation

### ISSUE THREAD

**Issue by ddliu365** [loco-3d/crocoddyl#919]
I checked #907 and found an argument of [FrameCoPSupport](https://github.com/loco-3d/crocoddyl/blob/85652cb24174b3184f23c1827a5e58b3c3f93444/include/crocoddyl/multibody/frames.hpp#L261) has not been synchronized with new `CoPSupport` by taking rotation matrix.
I guess we may follow this style:
```
copsupport = crocoddyl.CoPSupport(foot_rotation,foot_box)
copframe = crocoddyl.FrameCoPSupport(i, copsupport)
CoP = crocoddyl.CostModelContactCoPPosition(state, copframe, nu)
costModel.addCost("CoP", CoP, 1e1)
```
However, the function `crocoddyl.FrameCoPSupport(i, copsupport)` has not been updated yet.

**Comment by cmastalli** [comment]
Hi @ddliu365,

I did not update `FrameCoPSupport` (in #907) as this function will be deprecated soon.
Indeed, we are in the process of deprecating all `FrameXXX` structures as they add an unnecessary API complexity.
Part of this effort has been developed in #899.

I will close this issue as it won't lead to any action from our side.

**Comment by ddliu365** [comment]
ok, is there a way to apply cop cost with rotation matrix in current code?
or should I wait for another update

**Comment by cmastalli** [comment]
It would be possible after merging #899.
This PR might take us around 2 weeks for merging it (we need to check that everything is working properly).

**Comment by ddliu365** [comment]
Can I directly build the devel branch for this feature?
Is there an alternative way I can obtain this feature
