### ISSUE TITLE
MacOS installation through Homebrew

### ISSUE THREAD

**Issue by Neotriple** [loco-3d/crocoddyl#922]
Hi all,

Just curious if there are any plans of having Crocoddyl installed through the Homebrew package for installation through MacOS (similar to Pinocchio).

**Comment by jcarpent** [comment]
Conda is your best friend at this time!

**Comment by Neotriple** [comment]
Thanks, I didn't see that it was available through Conda either. Do you know how well this plays well with using it as a C++ library? I've only ever used Conda for Python environments.

**Comment by jcarpent** [comment]
It works like a charm. I'm now using Conda as the base source for all my project, and importantly, for developing Pinocchio! ;)

**Comment by Neotriple** [comment]
Great, thanks!

**Comment by Danfoa** [comment]
> It works like a charm. I'm now using Conda as the base source for all my projects, and importantly, for developing Pinocchio! ;)

@jcarpent Would you mind explaining how are you using conda to do source installs (i.e., being able to modify/compile and contribute to pinocchio/crocoddyl).

Though conda I can only install latest release not devel branches and furthermore packages are not editable, so no developing can be done.

**Comment by jcarpent** [comment]
You can simply do:
```
conda install crocoddyl -c conda-forge --only-deps
```
and in your crocoddyl build directory do:
```
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DPYTHON_EXECUTABLE=$(which python)
make install
```
