### ISSUE TITLE
MacOS installation through Conda

### ISSUE THREAD

**Issue by ddliu365** [loco-3d/crocoddyl#923]
I try to install the crocoddyl through Conda.

It comes with issues as shown in this log.
[crocoddyl_log.txt](https://github.com/loco-3d/crocoddyl/files/6165524/crocoddyl_log.txt)

**Comment by proyan** [comment]
Hi @ddliu365 This looks like a problem in your conda installation, and not crocoddyl.

**Comment by jcarpent** [comment]
I confirmed, croco is working well with conda install on macs.
The problem is on your side.

**Comment by ddliu365** [comment]
is there any specific version of Conda I should use?

I am using this python 3.8 [anaconda](https://repo.anaconda.com/archive/Anaconda3-2020.11-MacOSX-x86_64.sh)
```
Anaconda3-2020.11-MacOSX-x86_64
```

I also installed pinocchio which works well.

**Comment by ddliu365** [comment]
@jcarpent @proyan 
Thanks for your quick response.

I will check my side.

**Comment by jcarpent** [comment]
Should work with all versions. People from conda are doing an excellent job at this level.
We are not the best persons to answer your local computer problems.
