### ISSUE TITLE
Armature usage

### ISSUE THREAD

**Issue by andreadelprete** [loco-3d/crocoddyl#936]
I may be wrong, but at a first sight there seems to be a bug here:
https://github.com/loco-3d/crocoddyl/blob/cbf81a329e3abaf4ce1b4a8fab1431f93cd9a5c8/include/crocoddyl/multibody/actions/free-fwddyn.hxx#L65

When the variable `with_armature_` is false, then the armature is used, otherwise it's not used. Shouldn't it be the other way around?

**Comment by cmastalli** [comment]
Nice catched ;)

The code is correct is just the name of this internal variable is wrong. Could you create a PR that renames it to 'without_armature'?
