### ISSUE TITLE
ROS-CI does not yet run unittests

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#944]
We use `catkin_tools` as the `BUILDER` to avoid dependency resolution issues in the `upstream_ws` which contains `example-robot-data` (`colcon` would not resolve this correctly in CI). Alas, `catkin_tools` requires the `run_tests` target which we currently do not have. `colcon` would use `ctest` correctly on the other hand and works when manually sourcing the `upstream_ws` before building the `target_ws`. As such, right now there is no quick fix to run the unittests on the ROS-CI on GitHub Actions. This issue is to track this and be resolved at some point in the future. If anyone has a fix or suggestion, happy to go with it :-).

**Comment by cmastalli** [comment]
solved in #963
