### ISSUE TITLE
source file of multibody.hpp?

### ISSUE THREAD

**Issue by heli-sudoo** [loco-3d/crocoddyl#969]
Hello,

I created a planar monoped robot model using Pinocchio.robotwrapper, i.e.,  `robot = RobotWrapper.BuildFromURDF(
        start_path+URDF_PATH, model_path, pin.JointModelPlanar())`. The planar floating base needs three variables to specify its configuration, i.e., two translations (x,y) and one rotation (theta), whereas in the `robot model`, `robot.q0` needs four variables, i.e., x,y,sin(theta),cos(theta). However, when we create action models using 'robot', the state dimension should be 6 rather than 8. I see this is dealt with using `state =crocoddyl.StateMultibody(robot.model)` to get the correct state. Could you please point me to where I could find the implementation details of multibody? Currently I could only find the header file multibody.hpp but not the

**Comment by cmastalli** [comment]
Thank you for being interests in our project.
If you have questions about Pinocchio, please post it there.
If you need to find any source file of our project, you can use the search engine of github.
