### ISSUE TITLE
Issue with pip3 install

### ISSUE THREAD

**Issue by JaehyunShim** [loco-3d/crocoddyl#976]
Hi, 

I am trying to install crocoddyl using pip3 and the following is the error code I got. 
```sh
$ pip3 install --user crocoddyl
ERROR: Could not find a version that satisfies the requirement crocoddyl (from versions: none)
ERROR: No matching distribution found for crocoddyl
```

I am working on Ubuntu 20.04

Thanks,
Jaehyun

**Comment by nim65s** [comment]
Hi @JaehyunShim,

Your pip is too old to support the crocoddyl distributions from PyPI. You can fix this with:
```
python3 -m pip install --user --upgrade pip
python3 -m pip install --user crocoddyl
```

**Comment by cmastalli** [comment]
Closing this issue as it seems to be resolved!
