### ISSUE TITLE
Issue on non-constant angular momentum during aerial phase

### ISSUE THREAD

**Issue by zzhou387** [loco-3d/crocoddyl#979]
Hi folks,

Thanks for maintaining this awesome codebase first. I have been trying to generate some trajectories that involve aerial phases such as jumping or backflipping using crocoddyl. Since there is no contact force during the aerial phase, the angular momentum is supposed to be constant. The attached gif is one example I generated using crocoddyl:
![A1_jumping](https://user-images.githubusercontent.com/43147328/127109244-57f089a7-8877-49cd-9772-253a7a4a4fbf.gif)

However, when I plotted out the trajectory of angular momentum, it is not always constant:
![examp_1](https://user-images.githubusercontent.com/43147328/127112947-b699618f-a6a4-47dc-966a-64e8559128c4.png)

I was thinking it might be a numerical issue when integrating the dynamics, so I changed the timestep from 0.005 to 0.001. However, it didn't improve too much. It became even worse when the legs are jiggling during the aerial phase:
![A1_bonding](https://user-images.githubusercontent.com/43147328/127114214-3be10379-23e5-4ecb-b507-f0a4d7d318de.gif)
![examp_2](https://user-images.githubusercontent.com/43147328/127114239-13184fc0-bdf8-4578-9cf3-e9bd7aa598dd.png)

I am wondering whether you guys have ever noticed this issue before or maybe there is something wrong with my current optimization formulation. FYI, I only have EE and CoM position trackings during the aerial phase, and no contact model is added for both cases. I also double checked the contact forces are always zero during aerial phase.

Thanks a lot,
Ziyi

**Comment by cmastalli** [comment]
Hi Ziyi,


Thank you for being part of Crocoddyl community!

Would you let us know more details about your setup? Particularly I am interested to know about:
  - The value that you used for JMinvJt_damping
  - The integrator that you used it.

If this is the case, it would be interesting to report results for RK4 integrator with JMinvJt_damping equals zero.


Cheers,
Carlos

**Comment by proyan** [comment]
Could you please try after reinstalling the current devel version of pinocchio? I'm afraid if that might be because of https://github.com/stack-of-tasks/pinocchio/issues/1473, but just have to be sure.

**Comment by zzhou387** [comment]
> Hi Ziyi,
> 
> Thank you for being part of Crocoddyl community!
> 
> Would you let us know more details about your setup? Particularly I am interested to know about:
> 
> * The value that you used for JMinvJt_damping
> * The integrator that you used it.
> 
> If this is the case, it would be interesting to report results for RK4 integrator with JMinvJt_damping equals zero.
> 
> Cheers,
> Carlos

Thanks for your reply. The JMinvJt_damping has always been zero. I tried RK4 instead of Euler and it does help a lot. Now the AM is constant during the aerial phase. Here is the plotting for the second bonding example:
![Figure_11](https://user-images.githubusercontent.com/43147328/127291491-212b7eaa-8804-4ba7-bd21-d8083845c9bd.png)

Seems like the integration scheme matters a lot when integrating the momentum terms. thanks again!

**Comment by zzhou387** [comment]
> Could you please try after reinstalling the current devel version of pinocchio, and then reinstalling crocoddyl? I'm afraid if that might be because of [stack-of-tasks/pinocchio#1473](https://github.com/stack-of-tasks/pinocchio/issues/1473), but just have to be sure.

Thanks for letting me know this bug in analytical jacobian of centroidal momentum. I have fixed the non-constant issue by switching to RK4, but I'll do some benchmarks on the previous Euler case once I get a chance to reinstall everthing. I'll update you here.

**Comment by jcarpent** [comment]
A quick feedback. Your issue is not due to stack-of-tasks/pinocchio#1473 but rather to the drift induced by poor quality integrators. Using advanced scheme will help for sure. This is a well-known problem in Numercial Mechanics.

**Comment by jcarpent** [comment]
@zzhou387 What is the renderer you have been using so far?

**Comment by zzhou387** [comment]
> @zzhou387 What is the renderer you have been using so far?

This is in rviz.

**Comment by cmastalli** [comment]
> A quick feedback. Your issue is not due to [stack-of-tasks/pinocchio#1473](https://github.com/stack-of-tasks/pinocchio/issues/1473) but rather to the drift induced by poor quality integrators. Using advanced scheme will help for sure. This is a well-known problem in Numercial Mechanics.

Yes, indeed, I suspect this is the explanation, reason why I asked you to report results with RK4.

Generally speaking, numerical integrators inject energy in the systems.

Note that our Euler and RK4 integrators are the best that they could be (i.e., simpletic schemes) as we need to keep the Markovian structure in DDP-like algorithms.

**Comment by cmastalli** [comment]
> @zzhou387 What is the renderer you have been using so far?

@jcarpent --- please have a look on an Rviz plugin that I developed:  https://github.com/loco-3d/whole_body_state_rviz_plugin

Indeed, I am planning to develop a Python callback function (to avoid ROS dependencies at compile time) as I am very unsatisfied with GepettoViewer (e.g., cannot display motions at real-time, code under development). Note that we are heavily using the plugin in our developments.

**Comment by jcarpent** [comment]
On our side, we are about to add the support of RVIZ in Python for easy visualisation within Pinocchio.
This will help everybody, without having to write C++ code.

**Comment by cmastalli** [comment]
> On our side, we are about to add the support of RVIZ in Python for easy visualisation within Pinocchio.
> This will help everybody, without having to write C++ code.

We could indeed develop this in Pinocchio (rather than Crocoddyl). If you like this solution, I will be keen to work on it asap. Let's schedule a meeting if this is in your interest.

**Comment by jcarpent** [comment]
Yes, sure.
