### ISSUE TITLE
URDF not represented correctly in gepetto-GUI

### ISSUE THREAD

**Issue by VasilyRakche** [loco-3d/crocoddyl#985]
Hi, 
I am working on my own legged robot and wanted to try out your solution for control, but I have problems when I try to use [my urdf and srdf files.](https://github.com/Legged-robot/robot_description_package) I have made quite simple robot representation and verified that it is correctly shown in RVIZ:
![image](https://user-images.githubusercontent.com/30003101/128627205-466c10c3-38b8-4f2d-a525-84f4b66227ff.png)

I used your script `example_robot_data` to upload my robot with this configurations:
```
class FOREloader(RobotLoader):
    path = 'robot_simple_description'
    urdf_filename = "robot_simplified.urdf"
    srdf_filename = "robot_simplified.srdf"
    ref_posture = "standing"
    free_flyer = True
```
But what I get is that all links are placed at the origin:
![image](https://user-images.githubusercontent.com/30003101/128627285-9bf91e23-a15f-4fdb-947b-c17f0ae6dd64.png)

Also, I created my URDF based on the file provided by [ANYbotics anymal_b_simple_description ](https://github.com/ANYbotics/anymal_b_simple_description) and when I use [your adopted version from pinnochio](https://github.com/Gepetto/example-robot-data/tree/cac155e7fb266edfd57010df1c97b80e2473b89a/robots/anymal_b_simple_description), this is what I get (looks like the behavior is similar to what I get with my model, so I was wondering why): 

![image](https://user-images.githubusercontent.com/30003101/128627191-172ae6fd-78ef-49d9-ac14-1e2bc085bc8f.png)

**Comment by VasilyRakche** [comment]
I think all is good, it is expected from me to run 
```
robot.display(robot.q0)
```
Afterwards I get what I was expecting (still would be interested in short feedback from you if you think everything looks ok on the picture - one leg is modeled since I will be experimenting with one leg stand):
![image](https://user-images.githubusercontent.com/30003101/128627826-f112e652-ce71-4df3-991d-31da3d1295a5.png)

I just wander about one thing, why you [scale all the models with 1](https://github.com/Gepetto/example-robot-data/blob/cac155e7fb266edfd57010df1c97b80e2473b89a/robots/anymal_b_simple_description/robots/anymal.urdf#L169), but [in original it was scaled with 0.001](https://github.com/ANYbotics/anymal_b_simple_description/blob/988b5df22b84761bdf08111b1c2ccc883793f456/urdf/anymal.urdf#L93)? I hope it wont be too problematic to answer here so I wont be opening new issue somewhere else. Thank you.

**Comment by cmastalli** [comment]
Hey @VasilyRakche,

This issue doesn't belong to Crocoddyl.

Please post your issues in the corresponding project.
